services:
  backend-millennium-falcon:
    build: ./backend
    restart: unless-stopped
  frontend-millennium-falcon:
    build: ./frontend
    restart: unless-stopped


networks:
  default:
    external:
      name: global-network
