services:
  backend-millennium-falcon:
    build: ./backend
    volumes:
      - ./backend/millennium-falcon.json:/millennium-falcon.json
      - ./backend/universe.db:/universe.db
  frontend-millennium-falcon:
    build: ./frontend
    environment:
      - API_URL=https://api.millennium-falcon.raspberry78.me


networks:
  default:
    external:
      name: global-network
