services:
  backend-millennium-falcon:
    build: ./backend
    volumes:
      - ./backend/millennium-falcon.json:/millennium-falcon.json
      - ./backend/universe.db:/universe.db
  frontend-millennium-falcon:
    build: ./frontend


networks:
  default:
    external:
      name: global-network
