name: Deployment CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: staging

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: staging
